repos:
  - repo: local
    hooks:
      - id: black
        args: [--line-length=120]
        name: Running black
        entry: python -m black
        language: system
        types: [python]
      - id: flake8
        name: Running flake8
        entry: python -m flake8
        language: system
        types: [python]
